version: '3.4'

services:
  cleanarch.api:
    container_name: clean-arch-api
    image: jdorigoni/cleanarchapi
    build:
      context: .
      dockerfile: ../CleanArch.Api/Dockerfile
    ports:
      - 5005:80
    depends_on:
      - cleanarch.mvc

  cleanarch.mvc:
    container_name: clean-arch-mvc
    image: jdorigoni/cleanarchmvc
    build:
      context: .
      dockerfile: ../CleanArch.UI.Mvc/Dockerfile
    ports:
      - 5000:80
    depends_on:
      - database

  database:
    image: microsoft/mssql-server-linux:2017-CU3
    container_name: clean-arch-db
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"